version: '2'

services:
  nextcloud:
    image: wonderfall/nextcloud
    volumes:
      - /data/nextcloud:/data
      - /data:/user-files
  aria2:
    image: wahyd4/aria2-ariang:nextcloud
    ports:
      - "8000:80"
      - "6800:6800"
    volumes_from:
      - nextcloud
    links:
      - nextcloud:file-manager


