version: '2'

services:
  nextcloud:
    image: wonderfall/nextcloud
    ports:
      - "3000:8888"
    volumes_from:
      - aria2
    volumes:
      - /data/nextcloud:/data
  aria2:
    image: wahyd4/aria2-ariang
    ports:
      - "8000:80"
      - "6800:6800"
    volumes:
      - /data:/user-files


