version: '2'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: filerun
      MYSQL_USER: filerun
      MYSQL_PASSWORD: filerun
      MYSQL_DATABASE: filerun
    volumes:
      - /data/db:/var/lib/mysql
  web:
    depends_on:
      - db
    links:
      - db
    image: afian/filerun
    ports:
      - "3000:80"
    volumes:
      - /data:/user-files
  aria2:
    image: wahyd4/aria2-ariang
    ports:
      - "8000:80"
      - "6800:6800"
    volumes_from:
      - web

